project:
  type: book
  output-dir: docs


book:
  title: "R(D)SVS Quality Assurance and Enhancement Committee Chair Notes"
  author: "Jill MacKay"
  date: "17/08/2023"
  chapters:
    - index.qmd
    - c00about.qmd
    - part: c10induction.qmd
      chapters:
        - c11remit.qmd
        - c12membership.qmd
      appendices: references.qmd


bibliography: references.bib

format:
  html:
    theme: lux
  pdf:
    documentclass: scrreprt

editor: visual