project:
  type: book
  output-dir: docs


book:
  title: "R(D)SVS Quality Assurance and Enhancement Committee Chair Notes"
  author: "Jill MacKay"
  date: "17/08/2023"
  chapters:
    - index.qmd
    - c00about.qmd
    - part: c10induction.qmd
      chapters:
        - c11remit.qmd
        - c12membership.qmd
      appendices: references.qmd
    - part: c20meetings.qmd
      chapters:
        - c21conduct.qmd
        - c22papers.qmd
    - part: c30outputs.qmd
      chapters:
        - c31report.qmd
        - c32enhancement.qmd
    - part: c40misc.qmd
      chapters:
        - c41comms.qmd
  favicon: logo.png
  twitter-card: true
  site-url: https://jillymackay.github.io/chair-notes-vet-quality-assurance-committee/
  repo-url: https://github.com/jillymackay/chair-notes-vet-quality-assurance-committee
  repo-actions: [edit, issue, source]
  downloads: [pdf]
  sharing: [twitter, facebook]


bibliography: references.bib

format:
  html:
    theme: lux
  pdf:
    documentclass: scrreprt

editor: visual